// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contact.proto

package org.maciejmarczak.ds.rpc.server.protos;

public final class ContactOuterClass {
  private ContactOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Contact_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Contact_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcontact.proto\">\n\007Contact\022\017\n\007address\030\001 " +
      "\001(\t\022\024\n\014phone_number\030\002 \001(\t\022\014\n\004mail\030\003 \001(\tB" +
      "*\n&org.maciejmarczak.ds.rpc.server.proto" +
      "sP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Contact_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Contact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Contact_descriptor,
        new java.lang.String[] { "Address", "PhoneNumber", "Mail", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
