// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contact.proto

package org.maciejmarczak.ds.rpc.server.protos;

public interface ContactOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Contact)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string address = 1;</code>
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 1;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>string phone_number = 2;</code>
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>string phone_number = 2;</code>
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  /**
   * <code>string mail = 3;</code>
   */
  java.lang.String getMail();
  /**
   * <code>string mail = 3;</code>
   */
  com.google.protobuf.ByteString
      getMailBytes();
}
