// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package org.maciejmarczak.ds.rpc.server.protos;

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\032\rcontact.proto\"\213\001\n\004User\022\n\n\002" +
      "id\030\001 \001(\t\022\021\n\tfull_name\030\002 \001(\t\022\030\n\004role\030\003 \001(" +
      "\0162\n.User.Role\022\031\n\007contact\030\004 \001(\0132\010.Contact" +
      "\"/\n\004Role\022\013\n\007PATIENT\020\000\022\016\n\nTECHNICIAN\020\001\022\n\n" +
      "\006DOCTOR\020\002B*\n&org.maciejmarczak.ds.rpc.se" +
      "rver.protosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.maciejmarczak.ds.rpc.server.protos.ContactOuterClass.getDescriptor(),
        }, assigner);
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Id", "FullName", "Role", "Contact", });
    org.maciejmarczak.ds.rpc.server.protos.ContactOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
